# Generated by Django 3.2 on 2022-01-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='username',
        ),
    ]
